services:
  app:
    build: .
    ports:
      - "8081:8080" # Change the host port to 8081
    volumes:
      - .:/app
    environment:
      - GO_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - APP_PORT=8080 # Ensure APP_PORT is set to 8080 inside the container
